# 金融知识RAG问答系统 - Docker Compose配置
# ============================================
# 
# 功能说明:
# - 启动Milvus向量数据库服务
# - 启动MinIO对象存储服务
# - 启动etcd元数据服务
# - 提供完整的向量数据库基础设施
# 
# 服务组件:
# - Milvus: 向量数据库，用于存储和检索文档向量
# - MinIO: 对象存储，用于存储原始文档文件
# - etcd: 元数据存储，用于Milvus的元数据管理
# 
# 使用方法:
#   docker-compose up -d    # 后台启动所有服务
#   docker-compose down     # 停止所有服务
#   docker-compose logs     # 查看服务日志
# 
# 端口说明:
# - Milvus: 19530 (API), 9091 (Web UI)
# - MinIO: 9000 (API), 9001 (Web UI)
# - etcd: 2379 (API), 2380 (集群通信)
# 
# 数据持久化:
# - 所有数据存储在 ./volumes/ 目录下
# - 重启容器后数据不会丢失

version: '3.8'

services:
  # RAG Web应用
  rag-web:
    build: .
    container_name: rag-web
    ports:
      - "5000:5000"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - OLLAMA_HOST=http://106.52.6.69:11434
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
      - ./volumes:/app/volumes
    depends_on:
      - milvus-standalone
    restart: unless-stopped
    networks:
      - rag-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # etcd元数据服务
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd/milvus/etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    volumes:
      - etcd_data:/etcd
    restart: unless-stopped
    networks:
      - rag-network

  # MinIO对象存储服务
  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - rag-network

  # Milvus向量数据库
  milvus-standalone:
    image: milvusdb/milvus:v2.2.11
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      COMMON_STORAGETYPE: minio
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    restart: unless-stopped
    networks:
      - rag-network
    depends_on:
      - milvus-etcd
      - milvus-minio

volumes:
  milvus_data:
    driver: local
  etcd_data:
    driver: local
  minio_data:
    driver: local

networks:
  rag-network:
    driver: bridge