version: '3.8'

services:
  # RAG Web应用（连接到外部服务）
  rag-web:
    build: .
    container_name: rag-web
    ports:
      - "5000:5000"
    environment:
      - MILVUS_HOST=host.docker.internal
      - MILVUS_PORT=19530
      - OLLAMA_HOST=http://106.52.6.69:11434
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
      - ./volumes:/app/volumes
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 