apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: rag-system
spec:
  type: ClusterIP
  ports:
    - name: milvus-api
      port: 19530
      targetPort: 19530
    - name: milvus-web
      port: 9091
      targetPort: 9091
  selector:
    app: milvus-standalone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-standalone
  template:
    metadata:
      labels:
        app: milvus-standalone
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.3.11
          command: ["milvus", "run", "standalone"]
          ports:
            - containerPort: 19530
            - containerPort: 9091
          env:
            - name: ETCD_ENDPOINTS
              value: "milvus-etcd:2379"
            - name: MINIO_ADDRESS
              value: "milvus-minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: COMMON_STORAGETYPE
              value: "minio"
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
      volumes:
        - name: milvus-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd
  namespace: rag-system
spec:
  type: ClusterIP
  ports:
    - name: etcd-client
      port: 2379
      targetPort: 2379
  selector:
    app: milvus-etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-etcd
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-etcd
  template:
    metadata:
      labels:
        app: milvus-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.5
          command: ["etcd", "-advertise-client-urls=http://127.0.0.1:2379", "-listen-client-urls", "http://0.0.0.0:2379", "--data-dir", "/etcd/milvus/etcd"]
          ports:
            - containerPort: 2379
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd
      volumes:
        - name: etcd-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
  namespace: rag-system
spec:
  type: ClusterIP
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
    - name: minio-console
      port: 9001
      targetPort: 9001
  selector:
    app: milvus-minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-minio
  template:
    metadata:
      labels:
        app: milvus-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          args: ["server", "/minio_data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /minio_data
      volumes:
        - name: minio-data
          emptyDir: {} 