apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-web
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-web
  template:
    metadata:
      labels:
        app: rag-web
    spec:
      containers:
        - name: rag-web
          image: rag-autogen-rag-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: rag-config
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: data
              mountPath: /app/data
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: rag-web-uploads-pvc
        - name: data
          persistentVolumeClaim:
            claimName: rag-web-data-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: rag-web-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rag-web
  namespace: rag-system
spec:
  type: NodePort
  selector:
    app: rag-web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500 